name: Karate Tests

on:
  push:
    branches:
      - main  # Adjust branch name as per your default branch

jobs:
  test:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checks out your repository

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('swaglab/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'  # Specify the distribution

      - name: Install dependencies
        run: mvn install -DskipTests
        working-directory: swaglab  # Set the working directory to swaglab

      - name: Run Login Scenarios
        working-directory: swaglab  # Set the working directory to swaglab
        run: |
          mvn clean test -Dtest=TestEntireFlowRunner

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: swaglab/target/surefire-reports  # Adjust the path to your test reports
 
      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        with:
          name: test-summary-report
          path: swaglab/target/surefire-reports

      
