name: Karate Tests

on:
  push:
    branches:
      - main  # Adjust branch name as per your default branch

jobs:
  test:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checks out your repository

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('swaglab/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'  # Specify the distribution

      - name: Install dependencies
        run: mvn install -DskipTests
        working-directory: swaglab  # Set the working directory to swaglab

      - name: Run Login Scenarios
        working-directory: swaglab  # Set the working directory to swaglab
        run: |
          mvn clean test -Dtest=TestEntireFlowRunner

      - name: Generate Test Report
        run: |
          echo "Generating test report..."
          # Here you would generate your report file, for example:
          echo "Test results summary" > test-report.txt
          echo "Date: $(date)" >> test-report.txt
          echo "Test summary:" >> test-report.txt
          echo "Total tests: 10" >> test-report.txt
          echo "Passed: 8" >> test-report.txt
          echo "Failed: 2" >> test-report.txt
 
      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        with:
           name: test-summary-report
           path: swaglab/target/surefire-report
        
      
