name: Karate Tests

on:
  push:
    branches:
      - main  # Adjust branch name as per your default branch

jobs:
  test:
    runs-on: windows-latest  # Use Windows as the operating system

    steps:
      - uses: actions/checkout@v2  # Checks out your repository

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'  # Add the distribution input here

      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Run Login Scenarios
        working-directory: swaglab  # Adjust this to the relative path of your Maven project
        run: |
          mvn clean test -Dtest=TestEntireFlowRunner

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: target/surefire-reports  # Adjust the path to your test reports
