name: Karate Tests

on:
  push:
    branches:
      - main  # Adjust branch name as per your default branch

jobs:
  test:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checks out your repository

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('swaglab/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Find available port and start Chrome
        id: chrome
        run: |
          PORT=$(shuf -i 8000-9999 -n 1)
          echo "PORT=$PORT" >> $GITHUB_ENV
          google-chrome --remote-debugging-port=$PORT --headless --disable-gpu --no-sandbox &
        shell: bash

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'  # Specify the distribution

      - name: Install dependencies
        run: mvn clean install -DskipTests
        working-directory: swaglab  # Set the working directory to swaglab

      - name: Run Login Scenarios
        working-directory: swaglab  # Set the working directory to swaglab
        run: |
          mvn clean test -Dtest=TestEntireFlowRunner -Dmaven.test.failure.ignore=true

      #- name: Archive test results
       # if: always()
        #uses: actions/upload-artifact@v2
        #with:
         # name: test-results
          #path: swaglab/target/surefire-reports
      
      - name: Upload Surefire Test Report
        if: always()  # Always run this step
        uses: actions/upload-artifact@v2
        with:
          name: surefire-test-report
          path: swaglab/target/surefire-reports

      - name: Generate Karate Test Report
        if: always()  # Always run this step
        run: |
          mkdir -p karate-reports
          cp -r swaglab/target/karate-reports/* karate-reports/
        
      - name: Upload Karate Test Report
        if: always()  # Always run this step
        uses: actions/upload-artifact@v2
        with:
          name: karate-test-report
          path: karate-reports
        
      
